config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    get "bootstrap_docs" => "bootstrap_docs#index"
  end

  get "login/invalid" => "invalid_login#show", as: :invalid_login
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "redirector" => "redirectr#index"
  get "dashboard" => "dashboard#index"

  get "search" => "search#index"
  get "search/result/:id" => "search#show", as: :search_result

  namespace :find_this_item do
    resource :legal, only: [:show], controller: "legal"
    get 'test_cases' => "legal#index" if Rails.env.development?

    resource :request_help, only: [:create, :show], controller: "request_help"
  end

  namespace :print do
    get 'tickets_to_search' => "tickets_to_search#index"
  end

  namespace :patron do
    resources :request_search, only: [:new, :create, :show, :index]
    resources :my_tickets, only: [:index, :show]
  end

  namespace :manager do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :employees, only: [:show]
    resources :settings
  end

  namespace :coordinator do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :search_ticket, only: [:edit, :update, :show]
    resources :change_requestor, only: [:edit, :update]
    get 'tickets_by_status' => "tickets_by_status#index"
  end

  namespace :sl2 do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :search_ticket, only: [:edit, :update, :show]
    resource :start_search, only: [:update, :put]
    resources :change_requestor, only: [:edit, :update]
    get 'tickets_by_status' => "tickets_by_status#index"
  end

  namespace :sl1 do

    resource :dashboard, only: :show, controller: "dashboard"
    resource :start_search, only: [:update, :put]
    resources :search_ticket, only: [:edit, :update, :show]

    get 'tickets_by_status' => "tickets_by_status#index"

  end

  namespace :admin do
    resources :patrons
    resources :employees
    resources :locations
    resources :search_areas
    resources :search_tickets
  end

  root "redirector#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  # attributes:  name, email, location_id, role, login_id, active

  ## CONSTANTS
  ROLE_MANAGER="manager"
  ROLE_COORDINATOR="coordinator"
  ROLE_LEVEL_ONE ="service_level_one"
  ROLE_LEVEL_TWO ="service_level_two"
  ROLES = [ ROLE_MANAGER, ROLE_COORDINATOR, ROLE_LEVEL_ONE, ROLE_LEVEL_TWO ]

  ## RELATIONS
  belongs_to :location, optional: false

  has_many :tickets_in_location, -> (e) { where(location_id: e.location_id) }, foreign_key: "assigned_to_id", class_name: "SearchTicket"
  has_many :assigned_tickets, foreign_key: "assigned_to_id", class_name: "SearchTicket"
  has_many :work_logs, class_name: "SearchTicket::WorkLog"

  ## VALIDATIONS
  validates_uniqueness_of :login_id
  validates_presence_of :login_id, :name, :email, :role, :location_id

  ## SCOPES
  scope :by_role, -> { order(:role) }

  #callbacks
  after_create :create_patron_account


  ## METHODS
  def initials
    if name != nil
      return name.split(" ").map {|i|  i[0,1].capitalize }.join.ljust(2, "_")
    else
      return "##"
    end
  end

  def create_patron_account
    patron = Patron.build_new_user(login_id, email, name)
    patron.save(validate: false)
  end


  def patron
    Patron.find_by_login_id(login_id)
  end
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController <  Admin::AuthorizedBaseController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /admin/employees
  # GET /admin/employees.json
  def index
    @employees = Employee.all
  end

  # GET /admin/employees/1
  # GET /admin/employees/1.json
  def show
  end

  # GET /admin/employees/new
  def new
    @employee = Employee.new
  end

  # GET /admin/employees/1/edit
  def edit
  end

  # POST /admin/employees
  # POST /admin/employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to admin_employee_path(@employee), notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: admin_employee_path(@employee) }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/employees/1
  # PATCH/PUT /admin/employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to admin_employee_path(@employee), notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: admin_employee_path(@employee) }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/employees/1
  # DELETE /admin/employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to admin_employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :role, :email, :login_id, :location_id, :active)
    end
end

app/controllers/manager/authorized_base_controller.rb
class Manager::AuthorizedBaseController < AuthenticatedEmployeeController
  ## All Manager Processes will exetend from this controller
  ## This controller's job is to ensure only Coordinator Employees can access Coordinator Processes

  before_action :manager_employee_required

  private
  def manager_employee_required
    if current_user.role != Employee::ROLE_MANAGER
      redirect_to root_url, notice: "You are not authorized to use this part of the website"
    end
  end
end

app/controllers/manager/dashboard_controller.rb
class Manager::DashboardController < Manager::AuthorizedBaseController
  def show

    today = Time.zone.now.beginning_of_day..Time.zone.now.end_of_day
    yesterday = Time.zone.yesterday.beginning_of_day..Time.zone.yesterday.end_of_day
    @created_today = SearchTicket.where(created_at: today).count
    @resolved_today = SearchTicket.resolved_tickets.where(updated_at: today).count

    @created_yesterday = SearchTicket.where(created_at: yesterday).count
    @resolved_yesterday = SearchTicket.resolved_tickets.where(updated_at: yesterday).count

    @created_past_7_days = SearchTicket.created_past_7_days.count

    @resolved_past_7_days = SearchTicket.resolved_tickets.updated_past_7_days.count

  end
end

app/controllers/manager/employees_controller.rb
class Manager::EmployeesController < Manager::AuthorizedBaseController
  def show
    @employee = Employee.find(params[:id])

    @assigned_count = @employee.assigned_tickets.count
    @resolved_count = @employee.work_logs.resolved_found.count
    @under_review_count = @employee.work_logs.under_review.count
    @in_acquisitions_count = @employee.work_logs.in_acquisitions.count
  end
end

app/controllers/manager/settings_controller.rb
class Manager::SettingsController < Manager::AuthorizedBaseController
  before_action :get_setting, only: [:edit, :update]

  def index
    @settings = Setting.get_all
    @email_settings = Setting.get_all('email')
  end

  def edit
    @field_name = params[:id]
    @field_type = params[:field_type]
    @field_value = Setting[@field_name]
  end

  def update
    @field_name = params[:id]

    Setting[@field_name] = params[:setting][:value]
    notice = "Setting value has been updated"
    @field_value = Setting[@field_name]

    respond_to do |format|
      format.html { redirect_to admin_settings_path, notice: notice }
      format.js
    end

  end

  def get_setting
    @setting = Setting["#{params[:id]}"] || Setting.new(var: params[:id])
  end
end

app/views/manager/employees/_personal_details.html.erb
<ul class="list-group list-group-flush">
  <li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
      <div class="font-weight-bold">Name</div>
      <%= @employee.name %>
    </div>
  </li>
  <li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
      <div class="font-weight-bold">Role</div>
      <%= @employee.role.humanize.upcase %>
    </div>
  </li>
  <li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
      <div class="font-weight-bold">Email</div>
      <%= @employee.email %>
    </div>
  </li>
  <li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
      <div class="font-weight-bold">Location</div>
      <%= @employee.location.name rescue nil %>
    </div>
  </li>

  <li class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
      <div class="font-weight-bold">Access</div>

      <% if @employee.active? %>
        <p class="mb-0 text-success">Has Access</p>
      <% else %>
        <p class="mb-0 text-danger">Doesn't have access</p>
      <% end %>
    </div>
  </li>
  <li class="list-group-item">
      <%= link_to 'Make Changes', edit_admin_employee_path(@employee), class: "btn btn-outline-info btn-sm float-right" %>
  </li>
</ul>

app/views/manager/employees/_ticket_stats.html.erb
<ul class="list-group">
  <li class="list-group-item flex-column align-items-start">
    <h5 class="mb-1">Search Tickets</h5>
    <p class="mb-1 fs-90i">Tickets this employee is currently working on or has completed.</p>
  </li>

  <li class="list-group-item d-flex justify-content-between align-items-center">
    Assigned Search Tickets
    <span class="badge badge-primary badge-pill"><%= @assigned_count %></span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    Under Review
    <span class="badge badge-primary badge-pill"><%= @under_review_count %></span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    Resolved Tickets (Item Found)
    <span class="badge badge-primary badge-pill"><%= @resolved_count %></span>
  </li>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    Sent to Acquisitions
    <span class="badge badge-primary badge-pill"><%= @in_acquisitions_count %></span>
  </li>
</ul>

app/views/manager/employees/show.html.erb
<% page_title "Employee Details" %>
<%= bootstrap_card do %>
  <%= bootstrap_card_body title: @employee.name do %>
    <div class="card-subtitle mb-0 text-muted">
      <small>Last Logged In 3 days ago</small>
    </div>
    <hr/>

    <div class="row">
      <div class="col-md-6">
        <%= render partial: "ticket_stats" %>
      </div>
      <div class="col-md-6">
        <%= render partial: "personal_details" %>
      </div>
    </div>
  <% end %>
<% end %>