config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    get "bootstrap_docs" => "bootstrap_docs#index"
  end

  get "login/invalid" => "invalid_login#show", as: :invalid_login
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "redirector" => "redirectr#index"
  get "dashboard" => "dashboard#index"

  get "search" => "search#index"
  get "search/result/:id" => "search#show", as: :search_result

  namespace :find_this_item do
    resource :legal, only: [:show], controller: "legal"
    get 'test_cases' => "legal#index" if Rails.env.development?

    resource :request_help, only: [:create, :show], controller: "request_help"
  end

  namespace :print do
    get 'tickets_to_search' => "tickets_to_search#index"
  end

  namespace :patron do
    resources :request_search, only: [:new, :create, :show, :index]
    resources :my_tickets, only: [:index, :show]
  end

  namespace :manager do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :employees, only: [:show]
    resources :settings
  end

  namespace :coordinator do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :search_ticket, only: [:edit, :update, :show]
    resources :change_requestor, only: [:edit, :update]
    get 'tickets_by_status' => "tickets_by_status#index"
  end

  namespace :sl2 do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :search_ticket, only: [:edit, :update, :show]
    resource :start_search, only: [:update, :put]
    resources :change_requestor, only: [:edit, :update]
    get 'tickets_by_status' => "tickets_by_status#index"
  end

  namespace :sl1 do

    resource :dashboard, only: :show, controller: "dashboard"
    resource :start_search, only: [:update, :put]
    resources :search_ticket, only: [:edit, :update, :show]

    get 'tickets_by_status' => "tickets_by_status#index"

  end

  namespace :admin do
    resources :patrons
    resources :employees
    resources :locations
    resources :search_areas
    resources :search_tickets
  end

  root "redirector#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  # attributes:  name, email, address, phone

  ## CONSTANTS

  ## VALIDATIONS
  validates_presence_of :name, :email, :ils_code

  ## RELATIONS
  has_many :tickets, class_name: "SearchTicket"
  has_many :employees
  has_many :search_areas


  ## SCOPES
  scope :alpha, -> { order(name: :asc)}

  ## METHODS

end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController <  Admin::AuthorizedBaseController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to [:admin, @location], notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to [:admin, @location], notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to admin_locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :address, :email, :phone, :ils_code, :default_location)
    end
end

app/views/admin/locations/_form.html.erb
<%= form_with(model: [:admin, location], local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :location_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :location_address %>
  </div>

  <div class="field">
    <%= form.label :ils_code %>
    <%= form.text_field :ils_code, id: :location_ils_code %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :location_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :location_phone %>
  </div>

  <div class="field">
    <%= form.label :default_location %>
    <%= form.check_box :default_location, id: :default_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/locations/_list_as_table.html.erb
<table class="table table-striped table-sm">
  <thead class="">
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Address</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Ils code</th>
        <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
          <td><%= location.name %></td>
          <td><%= location.address %></td>
          <td><%= location.email %></td>
          <td><%= location.phone %></td>
          <td><%= location.ils_code %></td>
          <td><%= link_to 'Show', [:admin, location], class: 'btn btn-sm btn-primary' %></td>
          <td><%= link_to 'Edit', edit_admin_location_path(location), class: 'btn btn-sm btn-secondary' %></td>
          <td><%= link_to 'Destroy', [:admin, location], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', [:admin, @location] %> |
<%= link_to 'Back', admin_locations_path %>

app/views/admin/locations/index.html.erb
<% page_title "Locations - ADMIN" %>


<%= bootstrap_card do %>
  <%= bootstrap_card_header classes: "d-flex justify-content-between align-items-center" do %>
    Locations
    <%= link_to 'New Location', new_admin_location_path, class: 'btn btn-sm btn-success' %>
  <% end %>
    <%= render "list_as_table" %>
<% end %>

app/views/admin/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', admin_locations_path %>

app/views/admin/locations/show.html.erb
<% page_title "#{@location.class} Details" %>
<%= bootstrap_card do %>
  <%= bootstrap_card_body title: (defined?(@location.name)) ? @location.name : "Untitled Card" do %>
    <div class="card-subtitle mb-0 text-muted">
      <small>Location Subtitle</small>
    </div>
    <hr/>

    <div class="row">
      <div class="col-md-12">
  
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
              <div class="font-weight-bold">Name</div>
              <%= @location.name %>
            </div>
          </li>          
          <li class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
              <div class="font-weight-bold">Address</div>
              <%= @location.address %>
            </div>
          </li>          
          <li class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
              <div class="font-weight-bold">Email</div>
              <%= @location.email %>
            </div>
          </li>          
          <li class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
              <div class="font-weight-bold">Phone</div>
              <%= @location.phone %>
            </div>
          </li>          
          <li class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
              <div class="font-weight-bold">Ils code</div>
              <%= @location.ils_code %>
            </div>
          </li>          
        
          <li class="list-group-item">
            <%= link_to 'Make Changes', edit_admin_location_path(@location), class: 'btn btn-sm btn-primary' %>             
          </li>
        
        </ul>
        
      </div>
    </div>
  <% end %> <!-- card-body-->
<% end %> <!-- card -->