config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    get "bootstrap_docs" => "bootstrap_docs#index"
  end

  get "login/invalid" => "invalid_login#show", as: :invalid_login
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "redirector" => "redirectr#index"
  get "dashboard" => "dashboard#index"

  get "search" => "search#index"
  get "search/result/:id" => "search#show", as: :search_result

  namespace :find_this_item do
    resource :legal, only: [:show], controller: "legal"
    get 'test_cases' => "legal#index" if Rails.env.development?

    resource :request_help, only: [:create, :show], controller: "request_help"
  end

  namespace :print do
    get 'tickets_to_search' => "tickets_to_search#index"
  end

  namespace :patron do
    resources :request_search, only: [:new, :create, :show, :index]
    resources :my_tickets, only: [:index, :show]
  end

  namespace :manager do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :employees, only: [:show]
    resources :settings
  end

  namespace :coordinator do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :search_ticket, only: [:edit, :update, :show]
    resources :change_requestor, only: [:edit, :update]
    get 'tickets_by_status' => "tickets_by_status#index"
  end

  namespace :sl2 do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :search_ticket, only: [:edit, :update, :show]
    resource :start_search, only: [:update, :put]
    resources :change_requestor, only: [:edit, :update]
    get 'tickets_by_status' => "tickets_by_status#index"
  end

  namespace :sl1 do

    resource :dashboard, only: :show, controller: "dashboard"
    resource :start_search, only: [:update, :put]
    resources :search_ticket, only: [:edit, :update, :show]

    get 'tickets_by_status' => "tickets_by_status#index"

  end

  namespace :admin do
    resources :patrons
    resources :employees
    resources :locations
    resources :search_areas
    resources :search_tickets
  end

  root "redirector#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < AuthenticatedEmployeeController

  def index
    @search_query = q = params[:q]

    @tickets = SearchTicket.where(id: q).or(SearchTicket.where(item_id: q))
  end

  def show

    # this is a mini redirector to the proper place based on the level
    case current_user.role
    when Employee::ROLE_LEVEL_ONE
      url = sl1_search_ticket_url(params[:id])
    when Employee::ROLE_LEVEL_TWO
      url = sl2_search_ticket_url(params[:id])
    when Employee::ROLE_COORDINATOR
      url = coordinator_search_ticket_url(params[:id])
    when Employee::ROLE_MANAGER
      url = coordinator_search_ticket_url(params[:id])
    else
      url = dashboard_url
    end

    redirect_to url
  end
end

app/views/search/index.html.erb
<% page_title "Search Results" %>

<div class="p-3 bg-white rounded box-shadow">
  <h5 class="border-bottom border-gray pb-2 mb-0">
      Searching for Ticket or Item ID: <%= @search_query %>

      <span class="bg-status-new rounded text-white p-1 fs-70 float-right">
         Found:
        <span class="badge badge-light" data-search-results="<%= @tickets.size %>">
          <%= @tickets.size %>
        </span>
      </span>
  </h5>

  <div class="container">
    <% @tickets.each do |ticket| %>
      <div class="row pb-3 mb-0 pt-3 lh-125 border-bottom border-gray">
        <div class="col-sm-5">
          <%= ticket.id %>: <a href="<%= search_result_path(ticket) %>"><%= ticket.item_title %></a>
        </div>
        <div class="col-sm-2  text-center fs-90">
          <small class="font-weight-light text-muted">Callnumber</small><br/>
          <%= ticket.item_callnumber %>
        </div>
        <div class="col-sm-5  text-left fs-90">
          <small class="font-weight-light text-muted ">Status</small><br/>
          <%= ticket.ticket_status_description %>
        </div>
      </div>
    <% end %>

    <% if @tickets.size == 0 %>
    <div class="row pb-3 mb-0 pt-4 lh-125 border-bottom border-gray">
      <div class="col-sm-12  text-center fs-150i  text-muted font-weight-light">
        <p>We did not find any tickets matching your search query. </p>
      </div>
    </div>
    <% end %>
  </div>
</div>

<hr/>