config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    get "bootstrap_docs" => "bootstrap_docs#index"
  end

  get "login/invalid" => "invalid_login#show", as: :invalid_login
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "redirector" => "redirectr#index"
  get "dashboard" => "dashboard#index"

  get "search" => "search#index"
  get "search/result/:id" => "search#show", as: :search_result

  namespace :find_this_item do
    resource :legal, only: [:show], controller: "legal"
    get 'test_cases' => "legal#index" if Rails.env.development?

    resource :request_help, only: [:create, :show], controller: "request_help"
  end

  namespace :print do
    get 'tickets_to_search' => "tickets_to_search#index"
  end

  namespace :patron do
    resources :request_search, only: [:new, :create, :show, :index]
    resources :my_tickets, only: [:index, :show]
  end

  namespace :manager do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :employees, only: [:show]
    resources :settings
  end

  namespace :coordinator do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :search_ticket, only: [:edit, :update, :show]
    resources :change_requestor, only: [:edit, :update]
    get 'tickets_by_status' => "tickets_by_status#index"
  end

  namespace :sl2 do
    resource :dashboard, only: :show, controller: "dashboard"
    resources :search_ticket, only: [:edit, :update, :show]
    resource :start_search, only: [:update, :put]
    resources :change_requestor, only: [:edit, :update]
    get 'tickets_by_status' => "tickets_by_status#index"
  end

  namespace :sl1 do

    resource :dashboard, only: :show, controller: "dashboard"
    resource :start_search, only: [:update, :put]
    resources :search_ticket, only: [:edit, :update, :show]

    get 'tickets_by_status' => "tickets_by_status#index"

  end

  namespace :admin do
    resources :patrons
    resources :employees
    resources :locations
    resources :search_areas
    resources :search_tickets
  end

  root "redirector#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  # attributes:  name, email, address, phone

  ## CONSTANTS

  ## VALIDATIONS
  validates_presence_of :name, :email, :ils_code

  ## RELATIONS
  has_many :tickets, class_name: "SearchTicket"
  has_many :employees
  has_many :search_areas


  ## SCOPES
  scope :alpha, -> { order(name: :asc)}

  ## METHODS

end

app/models/patron.rb
class Patron < ApplicationRecord
  # attributes:  name, email, login_id

  ## CONSTANTS

  ## VALIDATIONS
  validates_uniqueness_of :login_id
  validates_presence_of :login_id, :name, :email

  ## RELATIONS
  has_many :search_tickets

  ## SCOPES

  ## METHODS


  def self.build_new_user(login_id, email, name)
    return Patron.new(name: name, login_id: login_id, email: email)
  end


  ## METHODS
  def initials
    if name != nil
      return name.split(" ").map {|i|  i[0,1].capitalize }.join.ljust(2, "_")
    else
      return "##"
    end
  end

  def is_also_employee?
    Employee.find_by_login_id(login_id) ? true : false
  end
end

app/controllers/coordinator/dashboard_controller.rb
class Coordinator::DashboardController < Coordinator::AuthorizedBaseController
  def show
    @under_review_tickets = current_user.location.tickets.under_review_tickets.recently_updated_first

    today = Time.zone.now.beginning_of_day..Time.zone.now.end_of_day
    yesterday = Time.zone.yesterday.beginning_of_day..Time.zone.yesterday.end_of_day
    @created_today = current_user.location.tickets.where(created_at: today).count
    @resolved_today = current_user.location.tickets.resolved_tickets.where(updated_at: today).count

    @created_yesterday = current_user.location.tickets.where(created_at: yesterday).count
    @resolved_yesterday = current_user.location.tickets.resolved_tickets.where(updated_at: yesterday).count

    @created_past_7_days = current_user.location.tickets.created_past_7_days.count  

    @resolved_past_7_days = current_user.location.tickets.resolved_tickets.updated_past_7_days.count
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < AuthenticatedEmployeeController
  def index  
  end

end

app/controllers/manager/dashboard_controller.rb
class Manager::DashboardController < Manager::AuthorizedBaseController
  def show

    today = Time.zone.now.beginning_of_day..Time.zone.now.end_of_day
    yesterday = Time.zone.yesterday.beginning_of_day..Time.zone.yesterday.end_of_day
    @created_today = SearchTicket.where(created_at: today).count
    @resolved_today = SearchTicket.resolved_tickets.where(updated_at: today).count

    @created_yesterday = SearchTicket.where(created_at: yesterday).count
    @resolved_yesterday = SearchTicket.resolved_tickets.where(updated_at: yesterday).count

    @created_past_7_days = SearchTicket.created_past_7_days.count

    @resolved_past_7_days = SearchTicket.resolved_tickets.updated_past_7_days.count

  end
end

app/controllers/sl1/dashboard_controller.rb
class Sl1::DashboardController < Sl1::AuthorizedBaseController
  def show
    @new_tickets = current_user.location.tickets.new_tickets.recently_updated_first
    @assigned_tickets = current_user.assigned_tickets.in_progress_tickets.recently_updated_first
  end
end

app/controllers/sl2/authorized_base_controller.rb
class Sl2::AuthorizedBaseController < AuthenticatedEmployeeController
  ## All SL2 Processes will exetend from this controller
  ## This controller's job is to ensure only SL2 Employees can access SL2 Processes

  before_action :sl2_employee_required

  private
  def sl2_employee_required
    if current_user.role != Employee::ROLE_LEVEL_TWO
      redirect_to root_url, notice: "You are not authorized to use this part of the website"
    end
  end
end

app/controllers/sl2/change_requestor_controller.rb
class Sl2::ChangeRequestorController < Sl2::AuthorizedBaseController

  def edit
    @patron = Patron.new
    @ticket = SearchTicket.find(params[:id])
  end

  def update
    @ticket = SearchTicket.find(params[:id])

    @patron = Patron.find_by_login_id(patron_params[:login_id])

    if @patron && @ticket.status != SearchTicket::STATUS_RESOLVED

      old_patron = Patron.find(@ticket.patron_id)
      @ticket.update_attribute(:patron_id, @patron.id)

      # create a work log
      @work_log = SearchTicket::WorkLog.new()
      @work_log.work_type = SearchTicket::WorkLog::WORK_TYPE_NOTE
      @work_log.employee = current_user
      @work_log.search_ticket = @ticket
      @work_log.result = SearchTicket::WorkLog::RESULT_PATRON_CHANGED
      @work_log.note = "Changed patron from #{old_patron.name} to #{@patron.name}"
      @work_log.save

    else
      # for now show an error and ask to for Patron to login first
      @error_message = "We could not find patron with that Login ID. To create a new patron, you should login to the patron portal first."
    end
  end


  def patron_params
    params.require(:patron).permit(:login_id)
  end
end

app/controllers/sl2/dashboard_controller.rb
class Sl2::DashboardController < Sl2::AuthorizedBaseController
  def show
    @escalated_tickets = current_user.location.tickets.escalated_tickets.recently_updated_first
    @assigned_tickets = current_user.assigned_tickets.in_progress_tickets.where(assigned_to_id: current_user.id).recently_updated_first
    @new_tickets = current_user.location.tickets.new_tickets.recently_updated_first
  end
end

app/controllers/sl2/search_ticket_controller.rb
class Sl2::SearchTicketController < Sl2::AuthorizedBaseController

  before_action :load_search_ticket
  before_action :check_ticket_status, only: :update

  def show
      @work_log = SearchTicket::WorkLog.new
  end

  def edit
    @work_log = SearchTicket::WorkLog.new
    render action: :show
  end

  def update

    @work_log = SearchTicket::WorkLog.new(work_log_params)
    @work_log.work_type = SearchTicket::WorkLog::WORK_TYPE_SEARCH
    @work_log.employee = current_user
    @work_log.search_ticket = @ticket

    # add search_ticket id to searched_areas
    @work_log.searched_areas.each do |sa|
      sa.search_ticket = @ticket
    end

    if @work_log.save

      if @work_log.result == SearchTicket::WorkLog::RESULT_FOUND
        @ticket.status = SearchTicket::STATUS_RESOLVED
        @ticket.resolution = SearchTicket::RESOLUTION_FOUND
        @ticket.save

      elsif @work_log.result == SearchTicket::WorkLog::RESULT_NOT_FOUND
        @ticket.status = SearchTicket::STATUS_REVIEW_BY_COORDINATOR
        @ticket.assigned_to_id = nil
        @ticket.save
      end


      redirect_to sl2_search_ticket_path(@ticket), notice: "Work Log recorded"
    else
      render action: :show
    end
  end

  private

  def load_search_ticket
    @ticket = current_user.location.tickets.find(params[:id])
  end

  def check_ticket_status
    if @ticket.status != SearchTicket::STATUS_SEARCH_IN_PROGRESS
      redirect_to sl2_search_ticket_path(@ticket), notice: "This ticket hasn't been assigned to anyone yet."
    end
  end

  def work_log_params
     params.require(:search_ticket_work_log).permit(:result, :found_location, :note, search_area_ids: [])
  end

end

app/controllers/sl2/start_searches_controller.rb
class Sl2::StartSearchesController < Sl2::AuthorizedBaseController

  def update
    ids = params[:search_ticket_ids]

    if ids.kind_of?(Array)
      ids.each do |id|
        ticket = SearchTicket.find(id)

        if allowed_ticket_status?(ticket)
          ticket.update(assigned_to: current_user, status: SearchTicket::STATUS_SEARCH_IN_PROGRESS)
        end

      end

      redirect_to sl2_dashboard_path, notice: "Assigned multiple search tickets to you!"
    else
      ticket = SearchTicket.find(ids)

      if allowed_ticket_status?(ticket)
        ticket.update(assigned_to: current_user, status: "#{SearchTicket::STATUS_SEARCH_IN_PROGRESS}")
      end

      redirect_to sl2_search_ticket_path(ticket)
    end

  end


  # def update
  #
  #   # Assign the new tickets to employee
  #   # update status of search_ticket(s) to SearchTicket::STATUS_SEARCH_IN_PROGRESS
  #   # Take user to My Search Tickets
  #
  #   if params[:search_ticket_ids]
  #
  #     ticket_ids = params[:search_ticket_ids]
  #
  #     if(ticket_ids.is_a?(Array))
  #       ## MULTIPLE TICKET IDS IS SELECTED
  #       ## Loop all items to ensure all are escalated tickets, otherwise redirect to New Tickets
  #       ticket_ids.each do |sreq|
  #         @ticket = SearchTicket.find(sreq)
  #         check_ticket_status(@ticket)
  #       end
  #
  #       # Update items to be assigned to current user and update status to in progress
  #       ticket_ids.each do |sreq|
  #         @ticket = SearchTicket.find(sreq)
  #         @ticket.update(assigned_to: current_user, status: "#{SearchTicket::STATUS_SEARCH_IN_PROGRESS}")
  #       end
  #     else
  #       ## "TICKET IDS IS SOLO"
  #       @ticket = SearchTicket.find(ticket_ids)
  #       check_ticket_status(@ticket)
  #       @ticket.update(assigned_to: current_user, status: "#{SearchTicket::STATUS_SEARCH_IN_PROGRESS}")
  #
  #     end ## is_a?(Array) close
  #
  #     redirect_to sl2_search_ticket_path(@ticket), notice: "Successfully assigned tickets"
  #
  #   else
  #     # redirect_to sl1_new_tickets_url, error: "Could not assign tickets due to Error."
  #     redirect_to sl2_dashboard_path, error: "Could not assign tickets due to Error."
  #   end
  #
  # end

  private

  def allowed_ticket_status?(ticket)
    allowed_statuses = [SearchTicket::STATUS_NEW, SearchTicket::STATUS_ESCALATED_TO_LEVEL_2]


    if !allowed_statuses.include?(ticket.status)
      return false
    else
      return true
    end
  end


end

app/controllers/sl2/tickets_by_status_controller.rb
class Sl2::TicketsByStatusController < Sl2::AuthorizedBaseController

  def index
    @status = params[:status]

    case @status
    when SearchTicket::STATUS_NEW
      @tickets = current_user.location.tickets.new_tickets.recently_updated_first
    when SearchTicket::STATUS_SEARCH_IN_PROGRESS
      @tickets = current_user.location.tickets.in_progress_tickets.recently_updated_first
    when SearchTicket::STATUS_ESCALATED_TO_LEVEL_2
      @tickets = current_user.location.tickets.escalated_tickets.recently_updated_first
    when SearchTicket::STATUS_REVIEW_BY_COORDINATOR
      @tickets = current_user.location.tickets.under_review_tickets.recently_updated_first
    when SearchTicket::STATUS_RESOLVED
      @tickets = current_user.location.tickets.resolved_tickets.recently_updated_first.limit(100)
    else
      @status = "unknown"
      @tickets = []
    end

  end
end

app/views/sl2/dashboard/_assigned_tickets.html.erb
<div class="p-3 bg-white rounded box-shadow">
  <h5 class="border-bottom border-gray pb-2 mb-0">Assigned To Me
    &nbsp;&nbsp;<%= link_to "Print Tickets", print_tickets_to_search_path(ticket_ids: @assigned_tickets.ids),
      class: "btn btn-sm btn-light fs-60i border", target: "_blank" %>

    <span class="bg-status-<%= SearchTicket::STATUS_SEARCH_IN_PROGRESS %> rounded text-white p-1 fs-70 float-right">
      <%= SearchTicket::STATUS_SEARCH_IN_PROGRESS.humanize %>
        <span class="badge badge-light" data-assigned-tickets-count="<%= @assigned_tickets.size %>">
          <%= @assigned_tickets.size %>
        </span>
    </span>
  </h5>

  <div class="container">
    <% if @assigned_tickets.size == 0 %>
      <p class="text-center mt-3">There are no tickets assigend to you at this moment.</p>
    <% end %>

    <% @assigned_tickets.each do |ticket| %>
      <div class="row pb-3 mb-0 pt-3 lh-125 border-bottom border-gray assigned_ticket_row">
        <div class="col-sm-7">
            <a href="<%= sl2_search_ticket_path(ticket) %>"><%= ticket.item_title %></a>
        </div>
        <div class="col-sm-2  text-center fs-90">
          <small class="font-weight-light text-muted">Callnumber</small><br/>
          <%= ticket.item_callnumber %>
        </div>
        <div class="col-sm-2  text-center fs-90">
          <small class="font-weight-light text-muted ">Last Updated</small><br/>
          <%= ticket.last_updated.strftime("%b %e, %Y") rescue nil%>
        </div>
        <div class="col-sm-1   text-center fs-90">
          <small class="font-weight-light text-muted">ID:   </small><br/>
          <%= ticket.id %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/sl2/dashboard/_escalated_tickets.html.erb
<div class="p-3 bg-white rounded box-shadow">
  <h5 class="border-bottom border-gray pb-2 mb-0">Recently Escalated Tickets

    <span class="bg-status-<%= SearchTicket::STATUS_ESCALATED_TO_LEVEL_2 %> rounded text-white p-1 fs-70 float-right">
      <%= SearchTicket::STATUS_ESCALATED_TO_LEVEL_2.humanize %>
        <span class="badge badge-light" data-escalated-tickets-count="<%= @escalated_tickets.size %>">
          <%= @escalated_tickets.size %>
        </span>
    </span>
  </h5>

  <div class="container">
    <% if @assigned_tickets.size == 0 %>
      <p class="text-center mt-3">There are no escalated tickets in the system currently.</p>
    <% end %>

    <%= form_tag sl2_start_search_path, method: :patch do %>
    <% @escalated_tickets.each do |ticket| %>
      <div class="row pb-3 mb-0 pt-3 lh-125 border-bottom border-gray escalated_ticket_row">
        <div class="col-sm-7">
            <a href="<%= sl2_search_ticket_path(ticket) %>"><%= ticket.item_title %></a>
        </div>
        <div class="col-sm-2  text-center fs-90">
          <small class="font-weight-light text-muted">Callnumber</small><br/>
          <%= ticket.item_callnumber %>
        </div>
        <div class="col-sm-2  text-center fs-90">
          <small class="font-weight-light text-muted ">Last Updated</small><br/>
          <%= ticket.last_updated.strftime("%b %e, %Y") rescue nil%>
        </div>
        <div class="col-sm-1   text-center fs-90">
          <small class="font-weight-light text-muted">ID:   <%= ticket.id %></small><br/>
          <%= check_box_tag "search_ticket_ids[]", ticket.id %>
        </div>
      </div>
    <% end %>
    <div class="row pb-2 mb-0 pt-3 lh-125">
      <div class="col-sm-12 text-right">
        <%= submit_tag "Assign & Start Search Now!", class: "btn btn-sm btn-success"%>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/sl2/dashboard/_new_tickets.html.erb
<div class="p-3 bg-white rounded box-shadow">
  <h5 class="border-bottom border-gray pb-2 mb-0">New Search Tickets

    <span class="bg-status-<%= SearchTicket::STATUS_NEW %> rounded text-white p-1 fs-70 float-right">
      <%= SearchTicket::STATUS_NEW.humanize %>
        <span class="badge badge-light" data-new-tickets-count="<%= @new_tickets.size %>">
          <%= @new_tickets.size %>
        </span>
    </span>
  </h5>

  <div class="container">
    <% if @assigned_tickets.size == 0 %>
      <p class="text-center mt-3">There are no new tickets in the system currently.</p>
    <% end %>

    <%= form_tag sl2_start_search_path, method: :patch do %>
    <% @new_tickets.each do |ticket| %>
      <div class="row pb-3 mb-0 pt-3 lh-125 border-bottom border-gray new_ticket_row">
        <div class="col-sm-7">
            <a href="<%= sl2_search_ticket_path(ticket) %>"><%= ticket.item_title %></a>
        </div>
        <div class="col-sm-2  text-center fs-90">
          <small class="font-weight-light text-muted">Callnumber</small><br/>
          <%= ticket.item_callnumber %>
        </div>
        <div class="col-sm-2  text-center fs-90">
          <small class="font-weight-light text-muted ">Created On</small><br/>
          <%= ticket.created_at.strftime("%b %e, %Y") %>
        </div>
        <div class="col-sm-1   text-center fs-90">
          <small class="font-weight-light text-muted">ID:   <%= ticket.id %></small><br/>
          <%= check_box_tag "search_ticket_ids[]", ticket.id %>
        </div>
      </div>
    <% end %>
    <div class="row pb-2 mb-0 pt-3 lh-125">
      <div class="col-sm-12 text-right">
        <%= submit_tag "Assign & Start Search Now!", class: "btn btn-sm btn-success"%>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/sl2/dashboard/show.html.erb
<% page_title "Dashboard" %>

<div class="row">
  <div class="col-md-12">
    <%= render partial: "assigned_tickets" %>
    <hr/>
  </div>



  <div class="col-md-12">
    <%= render partial: "new_tickets" %>

    <hr/>
  </div>


  <div class="col-md-12">
    <%= render partial: "escalated_tickets" %>
  </div>
</div>